language: node_js
node_js:
  - '8'
  - '10'
  - 'node'
git:
  depth: 1
  quiet: true
env:
  - NODE_ENV=TEST CODECOV_TOKEN=ca7425b3-f889-45b7-9ee8-4da6ea51e0c6
cache:
  yarn: true
  directories:
    - 'node_modules'
scripts:
  - yarn test
after_success:
  - codecov
